In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a=[1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [6]:
b=[1,2.3,5]
b

[1, 2.3, 5]

In [7]:
np.array(b)

array([1. , 2.3, 5. ])

In [8]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [11]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
arr=np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [14]:
np.random.rand(10)

array([0.05115674, 0.0360658 , 0.74978961, 0.10007061, 0.79461427,
       0.4194725 , 0.782802  , 0.24094568, 0.61999065, 0.3795152 ])

In [15]:
np.random.randn(10)

array([-0.54323917, -1.49397206, -0.17928909,  0.59773209,  1.14686105,
       -0.1867517 ,  0.3909851 ,  0.84179234, -0.23688529,  2.10612499])

In [16]:
np.random.randint(10,20,10)

array([10, 13, 14, 11, 11, 19, 11, 10, 18, 19], dtype=int32)

In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [25]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [26]:
arr.mean()

np.float64(5.0)

In [27]:
arr.argmin()

np.int64(0)

In [28]:
arr.argmax()

np.int64(8)

In [29]:
arr.std()

np.float64(2.581988897471611)

In [30]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [31]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])