In [1]:
import numpy as np

In [2]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [3]:
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("sudoku row it is valid")

sudoku row it is valid


In [4]:
c=np.sum(s,axis=0)
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("sudoku column it is valid")

sudoku column it is valid


In [5]:
a=s[0:3,0:3]
a

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [6]:
np.sum(a,axis=1)

array([12, 15, 18])

In [7]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [8]:
import numpy as np
# columns: [age, Math Marks , science Mark]
data=np.array([
    [18,85,78],  #student1
    [19,92,88],  #student2
    [17,76,95],   #student3
    [18,65,70],  #student4
    [20,90,85]    #student5
])

In [9]:
data.shape

(5, 3)

In [10]:
data[:,1]

array([85, 92, 76, 65, 90])

In [11]:
np.mean(data[:,0])

np.float64(18.4)

In [12]:
data[:,1]

array([85, 92, 76, 65, 90])

In [13]:
np.max(data[:,2])

np.int64(95)

In [14]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [15]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [16]:
len(data[data[:,0] <19])

3

In [17]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [18]:
data[(data[:,1]>=80 )& (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [19]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [20]:
data[:,2][data[:,2] <75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])