In [3]:
import numpy as np

In [4]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [5]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [6]:
a1-a2

array([-5, -5, -5, -5, -5])

In [7]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
l=[1,2,3,4,5]
arr=np.array(l)

In [10]:
arr+10

array([11, 12, 13, 14, 15])

In [11]:
a=np.arange(1,21).reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [12]:
a+10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [13]:
a*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [27]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
slice=a[0:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
a
b=a.copy()

In [31]:
b[0]=99

In [19]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


In [35]:
A

array([[1, 2],
       [3, 4]])

In [36]:
B

array([[5, 6],
       [7, 8]])

In [40]:
A@B

array([[19, 22],
       [43, 50]])

In [41]:
A.T

array([[1, 3],
       [2, 4]])

In [42]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [44]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [47]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]